### ISSUE TITLE
No longer works with latest sublime linter

### ISSUE THREAD

**Issue by Temtaime** [veelo/SublimeLinter-contrib-dmd#1]
SublimeLinter: #5 SublimeLinter.sublime-package:838: dmd: No matches for regex: ^.+SublimeLinter3.+[(](?P<line>\d+)([,](?P<col>\d+))?[)]: (?:(?P<error>Error)|(?P<warning>Warning|Deprecation)): (?P<message>.+)\r?\n((.(?!SublimeLinter3))+\r?\n)*

**Comment by veelo** [comment]
Release v1.2.0 should resolve this.
